php-nginx:
  replicaCount: 1
  image:
    php:
      repository: ''
      tag: v1.0.45
    nginx:
      repository: bitnami/nginx
      tag: 1.19.1
  ports:
    php: 9000
    nginx: 8080
  service:
    name: nginx
  ingress:
    enabled: false
    hosts: {}
    annotations: null
    tls: null
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
