php-nginx:
  replicaCount: 1
  image:
    php:
      repository: javierjafio/sample-php
      tag: v1.0.3
    nginx:
      repository: bitnami/nginx
      tag: 1.19.1
  ports:
    php: 9000
    nginx: 8080
  service:
    name: nginx
  ingress:
    enabled: false
    tls:
      enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
