php-nginx:
  replicaCount: 1
  image:
    php:
      repository: "javierjafio/sample-php"
      tag: v1.0.45
    nginx:
      repository: bitnami/nginx
      tag: 1.19.1
  ports:
    php: 9000
    nginx: 8080
  service:
    name: nginx
  ingress:
    enabled: true
    hosts:
     - sample-php-1.apps.barberbooks.com
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    tls: 
     enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
